### ISSUE TITLE
auto keybinding issues

### ISSUE THREAD

**Issue by DLAcoding** [Matrixchung/EDAutopilot#13]
As many other players in ED I have a josytick to play. My primary controls usually are mapped to it but not all. I assume its only parsing the primary?

    Parsing keybinds: Custom
    JOY_3 is not in SCANCODE list!!
    POS_JOY_RZAXIS is not in SCANCODE list!!
    NEG_JOY_RZAXIS is not in SCANCODE list!!
    JOY_POV1UP is not in SCANCODE list!!
    JOY_POV1RIGHT is not in SCANCODE list!!
    KEY_ENTER is not in SCANCODE list!!
    JOY_2 is not in SCANCODE list!!
    JOY_POV1LEFT is not in SCANCODE list!!
    JOY_POV1UP is not in SCANCODE list!!
    JOY_POV1DOWN is not in SCANCODE list!!
     is not in SCANCODE list!!
     is not in SCANCODE list!!
    Error in setting keybind(s): ['UI_Back', 'Pause']
    Successfully added 24 keybinds, 2 failed.

**Comment by SumZer0-git** [comment]
it looks like the code does a keyTranslate()  which will output this error message but then checks to see if the type is primaryDevice == Keyboard and if not jumps down to secondaryDevice and check to see if that is a Keyboard type.   So it looks like it works but need to clean up the invalid error messages

**Comment by Matrixchung** [comment]
Fixed. Now the keyTranslate() will only kick in if the device == 'Keyboard'
