### ISSUE TITLE
'ScriptSession' object has no attribute 'update'

### ISSUE THREAD

**Issue by supermopf** [Matrixchung/EDAutopilot#20]
Hey there, 

the method ScriptSession.update() does not exist. 

```
[12:52:50][WARN] Traceback (most recent call last):
  File "C:\Users\super\Desktop\EDAutopilot\scripts\robigo.py", line 273, in run
    session.update()
AttributeError: 'ScriptSession' object has no attribute 'update'
```

I don't know if this is related to this issue, but when I run robigo.py the script crashes just before selecting "Pick Cabin"

Have a nice day,
supermopf

**Comment by Matrixchung** [comment]
Sorry for inconvenience.
Just remove all `session.update()` since now every update is event-driven and there's no need to manually trigger update()

**Comment by Matrixchung** [comment]
13df2223923278c48f32e038202c8f79008d751b
