### ISSUE TITLE
Keybinding mappings

### ISSUE THREAD

**Issue by SumZer0-git** [Matrixchung/EDAutopilot#7]
In the keybinds.py file, it is not clear what the following keys are to be mapped to in the game

```py
    'space': 0x39,                          # what ED function?   
    'UI_1': 0x02, # Key 1               # Are these four associated with UI panel selection?
    'UI_2': 0x03, # Key 2
    'UI_3': 0x04, # Key 3
    'UI_4': 0x05, # Key 4
    'enter': 0x1C, # Key RETURN(ENTER)             # doesn't seem to be used
    'esc': 0x01, # Key ESC                                     # is there a specific ED function?
```

**Comment by Matrixchung** [comment]
Some buttons are game-related (like UI_xx and movements) which need to be set in game, while 'space' 'enter' and 'esc' are just keys mapped in scancode.
In early tests, I used fixed keymappings just for convenience.
Will soon implement the user keybindings.

**Comment by Matrixchung** [comment]
see 8321410317761410083aa09a03bab9a872e45ad7
