### ISSUE TITLE
Using user keybindings

### ISSUE THREAD

**Issue by SumZer0-git** [Matrixchung/EDAutopilot#8]
Recommending using either skai's  routines that process user key bindings (in dev_autopilot.py: get_latest_keybinds(), get_bindings())  or the sumzer0-git  EDKeys.py (https://github.com/SumZer0-git/EDAPGui.git. which puts skia's functions into a class).  These routines looks up the users key bindings for the required ED functionality.   This way we won't have to change our bindings between APs

**Comment by Matrixchung** [comment]
Yes, see reply in #7

**Comment by Matrixchung** [comment]
Implemented my own.
see 8321410317761410083aa09a03bab9a872e45ad7
