### ISSUE TITLE
when High -value mission is found enters in a loop

### ISSUE THREAD

**Issue by DLAcoding** [Matrixchung/EDAutopilot#9]
When a high-value mission is detected, it goes back to the mission panel and keep selecting the same mission. I am not sure if is related to the offsets or the way the logic works. 

    result = locateImageInGame(mission_dest,confidence=0.7)
    result1 = locateImageInGame(mission_destHL,confidence=0.7)
    if result[0]==-1 and result1[0]==-1: break # No more mission
    if result1[0]!=-1: pyautogui.moveTo(result1[0]-200,result1[1]) 
    else: pyautogui.moveTo(result[0]-200,result[1])

As I understand it sais:
- Find both mission_dest and mission_destHL.
- IF you cannont find any means there are no more missions available in the screen, break the loop (and go next provider).
- IF there is a highlight mission click it -> I think here is the problem: when you go back from a mission where you found a hight-value target, that mission keeps highlighted and the loop will enter again as it first looks for a highlight mission.
- ELSE select the not highligh mission

**my solution**: What I did was simply add a `UI_Down` to make sure that the next mission at the bottom will be the highlighted

    else: # high-value
      if isDebug: print("get-mission: High-value target detected")
      mouseClick(getAbsoluteCoordByOffset(windowCoord,offset_button_reward_back))
      # Now go one down to avoid infinite loop in the same mission
      session.sendKey('UI_Down')
      session.sendDelay(1)

**Comment by Matrixchung** [comment]
Fixed in 9ca57d0a25a74c1b4dbeb4ac6e2d1c1c791cf89c
